### ISSUE TITLE
Format using ISO Code

### ISSUE THREAD

**Issue by sliekens** [AutomateValue/NodaMoney#46]
At the moment, ToString formats money using its currency symbol, but symbols can be ambiguous. Please add a method that formats money using its unambiguous currency code instead.

See wikipedia's section on formatting rules: https://en.wikipedia.org/wiki/ISO_4217#Position_of_ISO_4217_code_in_amounts

In my opinion, formatting using the ISO code should have been the default result of calling `Money.ToString()` and formatting using the currency symbol should have been the result of calling `Money.ToString("C")`

**Comment by remyvd** [comment]
I agree symbols (signs) can be ambiguous, but this is what people expect when looking at money. The symbol primarly defines that a value represents money. That money later is formalized by ISO with codes and numbers, doesn't take this away.

The ISO code is only used in edge cases, where it must be totally clear which currency is used (legal, exchange, etc). Also NodaMoney can be used by non-ISO currencies like bitcoin or your own imaginary currency like some game currency or facebook coins. So I don't think `Money.ToString()` should by default give the ISO code, but instead should give the symbol.

Also using `Decimal.ToString("C")` the number is formatted with the currency symbol, which means the symbol is the default what people expect.

Of course NodaMoney should support formatting with the ISO code, which was already on the planning, but because Format Pattern Strings can be a complex job. There is a way to do it by using `string.Format("{0} {1}", money.Code, money.Amount)`, so that the reason I postponed it ;-).

I was thinking about adding a couple of Standard Money Format Strings:

Format specifier | Description | Examples
------------ | ------------- | -------------
C | currency symbol pattern | € 23.002,43 , € 23,002.43
I  | currency code pattern | EUR 23.002,43 , EUR 23,002.43 , 23.002,43 EUR
O | Round-trip money pattern | EUR 23002,43
N | Number pattern | 23.002,43 , 23,002.43
F | currency english name pattern | 23.002,43 dollar
f | currency native name pattern | 23.002,43 dólar

**Comment by carlosschults** [comment]
Hey, all. I'd like to start contributing to NodaMoney. Can I have a try at implementing one of the Format Strings?

**Comment by remyvd** [comment]
Yes, all help is welcome. Send it as a pull request. Thanks!

**Comment by remyvd** [comment]
Format C, I and F are working, see https://github.com/remyvd/NodaMoney/blob/master/tests/NodaMoney.Tests/MoneyFormattableSpec.cs
